apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend3-peyraga
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend3-peyraga
  template:
    metadata:
      labels:
        app: backend3-peyraga
    spec:
      containers:
        - name: backend3-peyraga
          image: ragepay/backend3-peyraga:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: backend3-peyraga-service
spec:
  selector:
    app: backend3-peyraga
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort